### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by atroche** [gowravshekar/bootstrap-webpack#12]
```javascript
ERROR in ./~/bootstrap-webpack/bootstrap-scripts.loader.js!./~/bootstrap-webpack/bootstrap.config.js
Module build failed: Error: Cannot find module '/Users/aroche/Code/other/aussie-schools/node_modules/babel-loader/index.js!/Users/aroche/Code/other/aussie-schools/node_modules/bootstrap-webpack/bootstrap.config.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.module.exports.pitch (/Users/aroche/Code/other/aussie-schools/node_modules/bootstrap-webpack/bootstrap-scripts.loader.js:20:16)
 @ ./~/bootstrap-webpack/index.js 4:0-52
```

Any clues? Here's my package.json:

```javascript
{
  "name": "table",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "./node_modules/.bin/webpack -p --progress",
    "watch": "./node_modules/.bin/webpack -p --watch --progress",
    "watch-dev": "./node_modules/.bin/webpack --watch --progress",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel": "^4.7.16",
    "babel-core": "^4.7.16",
    "babel-loader": "^4.2.0",
    "bootstrap": "^3.3.4",
    "bootstrap-webpack": "0.0.3",
    "css-loader": "^0.10.1",
    "event-emitter": "^0.3.3",
    "file-loader": "^0.8.1",
    "fixed-data-table": "^0.1.2",
    "flux": "^2.0.1",
    "lodash": "^3.6.0",
    "papaparse": "git://github.com/mholt/PapaParse.git#master",
    "react": "^0.13.1",
    "style-loader": "^0.10.1",
    "url-loader": "^0.5.5",
    "webpack": "^1.8.4"
  }
}
```

**Comment by klacointe** [comment]
https://github.com/gowravshekar/bootstrap-webpack/issues/3#issuecomment-77813247
